Алексей Егоров
VictoriaOtm/e2e-js-2021-1 pull request #33
Opened 2021-10-21 18:39 UTC by pekanboy

2021-10-21 18:50 UTC, astlok commented on cases/login_test.js
> +});
пустую строку в конце

2021-10-21 18:50 UTC, astlok commented on cases/search_test.js
> +        for (let item of received) {
цикл убратб

2021-10-21 18:50 UTC, astlok commented on cases/search_test.js
> +        for (let item of received) {
должен быть в степах

2021-10-21 18:50 UTC, astlok commented on cases/logout_test.js
> +});
пустую строку в конце

2021-10-21 18:50 UTC, astlok commented on cases/search_test.js
> +});
пустую строку в конце

2021-10-21 18:50 UTC, astlok commented on pages/search.js
> +export default new SearchPage()
пустую строку в конце

2021-10-21 18:50 UTC, astlok commented on steps/search.js
> +export default new SearchSteps();
пустую строку в конце

2021-10-21 18:50 UTC, astlok commented on cases/logout_test.js
> +        const isAuth = !!account.logout();
отвратительная запись

2021-10-21 18:50 UTC, astlok commented on cases/search_test.js
> +        for (let item of received) {
и вообще в ваших этих джава скриптах принято юзать forEach я слышал

2021-10-22 18:23 UTC, lev4rT requested changes

2021-10-22 18:23 UTC, lev4rT commented on pages/account.js
> +			error404: '.page404__title',
Привязка к классу. Но нейминг классов похож на БЭМ, поэтому думаю ок

2021-10-22 18:23 UTC, lev4rT commented on steps/search.js
> +        }
Думаю, стоит добавить `break`, при выполнении условия в `if`

2021-10-22 18:28 UTC, pekanboy commented on steps/search.js
> +        }
точно)

2021-10-22 18:57 UTC, lev4rT approved these changes

2025-03-03 10:09 UTC, closed without merging