Евдокимов Арсений
VictoriaOtm/e2e-js-2021-1 pull request #4
Opened 2021-04-01 18:02 UTC by Arugaf

2021-04-01 18:52 UTC, shysa reviewed
Все вроде хорошо
Но не уверена насчет того, что тестировать изменение описания профиля через process.env - хорошая идея (не очень наглядно, с логином/паролем понятно - хранить их нельзя и они индивидуальны, а вот описание, думаю, логичнее было бы вставить непосредственно как const в it-тесте)

2021-04-01 20:21 UTC, mark-by requested changes

2021-04-01 20:21 UTC, mark-by commented on pages/account.js
> +        );
Тестов в PageObject быть не должно( Их надо бы вынести либо в сами тесты, либо в steps, но кажется лучше в сами тесты

2021-04-01 20:21 UTC, mark-by commented on pages/profile.js
> +    }
аналогично

2021-04-02 12:23 UTC, Arugaf commented
Пофиксил.

2021-04-02 14:54 UTC, mark-by approved these changes
кайф

2021-04-12 07:51 UTC, VictoriaOtm commented on cases/profile_editing_test.js
> +        assert.strictEqual(
этот ассерт прям просится в степ auth, тебе же тогда не нужно будет его копипастить, представь, что ты бы писал 10 тестов, во всех 10 ты авторизуешься в beforeEach

2021-10-21 12:10 UTC, closed without merging