3 теста (1 авторизация, 2 - обработка ошибок в вакансии)
VictoriaOtm/e2e-js-2021-1 pull request #6
Opened 2021-04-01 18:39 UTC by H-b-IO-T-O-H

![Снимок экрана от 2021-04-01 21-37-19](https://user-images.githubusercontent.com/56133777/113339079-a45ae400-9332-11eb-8a49-a524eff2aad9.png)

2021-04-01 20:47 UTC, shysa requested changes

2021-04-01 20:47 UTC, shysa commented on cases/vacancy_test.js
> +        account.login();
А если не получилось зайти за пользователя? Если я правильно поняла, openVacancyCreation будет ждать появления кнопки создания вакансии, но это будет только в том случае, если пользователь успешно зашел. А если у него не получилось, то кнопки не будет, тест-Хатико :( 
Наверное, нужно отлавливать это еще на этапе beforeEach, сделав у account метод auth, который все это будет делать (открывать страницу, логиниться и проверять успешный вход)

2021-04-01 20:47 UTC, shysa commented on pages/authorization/authorization.js
> +            userEmail: 'div[id="email"]',
Элемент с id - уникальный на странице, к нему можно обращаться по селектору `userEmail: '#email' ,`
Аналогично с другими здесь и в profile.js

2021-04-01 20:47 UTC, shysa commented on pages/vacancy/vacancy.js
> +        this.page.setValue(vacancyTitleSelector, "some title"); // заполняем некоторые поля формы вакансии (заголовок)
Тут, наверное, все-таки стоит разделить на функции именно проверки и функции заполнения полей. Тогда и в steps/vacancy.js create'ы будут выглядеть логичнее: будет видно, как и какие поля пошагово заполняются, а затем происходит какой-то чек

2021-04-01 20:47 UTC, shysa commented on pages/authorization/authorization.js
> +        const emailSelector = this.locators.email;
Не уверена, что это хорошая идея. В принципе, напрямую обращение к переменным this.locators не усложняет восприятие, а кода немножко меньше

2021-04-02 10:20 UTC, H-b-IO-T-O-H commented on cases/vacancy_test.js
> +        account.login();
Все тесты в рамках работы с формой вакансии доступны только авторизованому пользователю-работодателю. Сейчас 2 теста, при этом 1 вход в аккаунт. Зачем выполнять попытки входа перед каждым тестом? Если тестов будет больше, то это довольно сильно будет сказываться на времени. Тут я проверяю не логин, а именно работу с формой вакансии. Я специально вынес это в отдельный кейс. Но вот насчет того, что не стоит ждать появления кнопки создания вакансии соглашусь. Вынес в before проверку на успешный логин. :) Но в любом случае от теста-Хатико так просто не избавиться, ибо  в случае неудачного логина - нужно ждать появления той же ошибки через waitForVisible. Поэтому в случае некорректного логина, метод будет 1.5 секунды ждать,  а не 10. Как сделать лучше - не знаю

2021-04-02 10:22 UTC, H-b-IO-T-O-H commented on pages/authorization/authorization.js
> +            userEmail: 'div[id="email"]',
Да, но мне больше нравится явно указывать, что к какому блоку привязано. Разница не существенна, на мой взгляд

2021-04-02 10:30 UTC, H-b-IO-T-O-H commented on pages/vacancy/vacancy.js
> +        this.page.setValue(vacancyTitleSelector, "some title"); // заполняем некоторые поля формы вакансии (заголовок)
Согласен, вынес заполнение в отдельный метод класса. И вызываю его как отдельный шаг в steps

2021-04-02 10:33 UTC, H-b-IO-T-O-H commented on pages/authorization/authorization.js
> +        const emailSelector = this.locators.email;
Мне кажется норм, кода больше на одну сточку, и не надо несколько раз писать this.locators.selctor ... Дело вкуса, на мой взгляд.

2021-04-02 10:49 UTC, shysa approved these changes

2021-04-02 12:26 UTC, Arugaf commented
LGTM

2021-04-02 21:33 UTC, H-b-IO-T-O-H commented on cases/vacancy_test.js
> +        account.login();
Все-таки правильнее будет с beforeEach, исправил.

2021-04-12 07:26 UTC, VictoriaOtm commented on cases/vacancy_test.js
> +    it('Ошибка при вводе зарплаты, когда min > max', () => {
Каждый тест (it) выносим в отдельный файл, кажется как раз с тобой это обсуждали в телеге. Если тебя тревожит копипаста, то в этом конкретном кейсе метод создания вакансии можно было бы сделать универсальным, чтобы он принимал аргумент, тогда можно было бы использовать аналог it.each в юнитах - инструмент given из пакета mocha-testdata, однако большая разница в том, что с given тоже поднимает новый хром и окружение 100% чистое. Так как здесь у нас нет этого инструмента, выносить надо в отдельный файлик.

2021-04-12 07:31 UTC, VictoriaOtm commented on pages/vacancy/vacancy.js
> +        const errorInvalidPhone = "Неверный номер телефона.";
а у этих полей нет локаторов? По тексту проверять очень не надежно, в реальных ситуациях тексты часто меняют, запускают с ними а/б тесты, поэтому всплывашки с ошибками имеют уникальные data-test-id атрибуты и по ним делаютс проверки в тестах

2021-04-12 07:32 UTC, VictoriaOtm commented on pages/vacancy/vacancy.js
> +        assert.deepStrictEqual(
только не делай ассерты в page в домашке, я промазала и добавила ассерт не в step, а page, Дима же просит все ассерты в самом тесте

2021-04-13 12:46 UTC, H-b-IO-T-O-H commented on cases/vacancy_test.js
> +    it('Ошибка при вводе зарплаты, когда min > max', () => {
Поправил, распределив тесты(it) по файлам. Возник вопрос, зачем тогда писать beforeEach, если в тестовом файле всегда один тест должен быть. 🤔

2021-04-13 12:52 UTC, H-b-IO-T-O-H commented on pages/vacancy/vacancy.js
> +        const errorInvalidPhone = "Неверный номер телефона.";
У полей есть локатор, но он только один) Ошибки на фронте сделаны в виде списка элементов без уникальных id и classname, разница только в содержимом. Я согласен насчет текста, но по-другому проверить не получится, т.к. все завязано на контенте элементов.
![Снимок экрана от 2021-04-13 15-49-31](https://user-images.githubusercontent.com/56133777/114555237-2c64b600-9c70-11eb-8fee-2557cd2625c1.png)
![Снимок экрана от 2021-04-13 15-50-52](https://user-images.githubusercontent.com/56133777/114555245-2e2e7980-9c70-11eb-801f-28f0cc47e1c0.png)

2021-04-13 12:53 UTC, H-b-IO-T-O-H commented on pages/vacancy/vacancy.js
> +        assert.deepStrictEqual(
Да, я знаю, поправил, в дз2, мы в page не держим asserts.)

2021-04-15 15:44 UTC, VictoriaOtm commented on cases/vacancy_test.js
> +    it('Ошибка при вводе зарплаты, когда min > max', () => {
Здесь можно и before, ты прав. Чисто семантически вернее писать beforeEach, потому что, например, будь у тебя здесь тот же given, авторизацию надо получать перед каждым тестом.

2021-04-15 15:46 UTC, closed without merging